import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { Bell, AlertTriangle, CheckCircle2, FileWarning, ShieldAlert, Check } from 'lucide-react';

export interface SystemNotification {
  id: string;
  title: string;
  message: string;
  type: 'compliance_warning' | 'payroll_alert' | 'document_expiry' | 'system_info';
  timestamp: string;
  isRead: boolean;
}

const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'NOTIF-01',
    title: 'Passport Expiry Alert (30 Days)',
    message: 'Employee Rashid Khan (EMP-ALH-001) passport expires on 2026-08-30. Please upload renewed passport copy.',
    type: 'document_expiry',
    timestamp: '10 mins ago',
    isRead: false,
  },
  {
    id: 'NOTIF-02',
    title: 'WPS Disbursement Deadline',
    message: 'July 2026 Monthly Payroll WPS SIF file must be uploaded to MOHRE portal before 3rd August to avoid late fines.',
    type: 'payroll_alert',
    timestamp: '2 hours ago',
    isRead: false,
  },
  {
    id: 'NOTIF-03',
    title: 'Geo-fencing GPS Check-in Alert',
    message: 'Employee Ayesha Siddiqui marked attendance within 45m radius of Dubai Head Office (Business Bay).',
    type: 'system_info',
    timestamp: '1 day ago',
    isRead: true,
  },
];

const NotificationCenter = () => {
  const [notifications, setNotifications] = useState<SystemNotification[]>(INITIAL_NOTIFICATIONS);

  const handleMarkAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, isRead: true })));
    toast.success('All notifications marked as read');
  };

  const handleMarkRead = (id: string) => {
    setNotifications((prev) => prev.map((n) => (n.id === id ? { ...n, isRead: true } : n)));
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 p-6">
      {/* Header */}
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-start md:items-center justify-between pb-6 border-b border-slate-200 gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Bell className="w-8 h-8 text-emerald-600" />
            <h1 className="text-2xl font-bold text-slate-900">Notification & Compliance Alert Center</h1>
            <Badge className="bg-emerald-500/20 text-emerald-700 border-emerald-500/30">
              Live Alerts
            </Badge>
          </div>
          <p className="text-slate-500 text-sm mt-1">
            Real-time notifications for MOHRE WPS deadlines, document expiries, and attendance compliance.
          </p>
        </div>

        <Button onClick={handleMarkAllRead} variant="outline" className="border-slate-200 text-slate-600 text-xs gap-1.5">
          <Check className="w-3.5 h-3.5" />
          Mark All as Read
        </Button>
      </div>

      <div className="max-w-7xl mx-auto mt-6">
        <Card className="bg-white border-slate-200">
          <CardHeader>
            <CardTitle className="text-lg font-semibold text-slate-900">System Notifications Queue</CardTitle>
            <CardDescription className="text-slate-500 text-xs">
              Automated alerts generated by compliance monitors and document expiration trackers.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {notifications.map((n) => (
                <div
                  key={n.id}
                  className={`border rounded-lg p-4 flex flex-col md:flex-row md:items-center justify-between gap-3 transition ${
                    n.isRead ? 'bg-slate-50/60 border-slate-200/80 text-slate-500' : 'bg-slate-50 border-emerald-500/30 text-slate-900'
                  }`}
                >
                  <div className="flex items-start gap-3">
                    {n.type === 'document_expiry' ? (
                      <FileWarning className="w-5 h-5 text-amber-600 mt-0.5 shrink-0" />
                    ) : n.type === 'payroll_alert' ? (
                      <AlertTriangle className="w-5 h-5 text-rose-600 mt-0.5 shrink-0" />
                    ) : (
                      <CheckCircle2 className="w-5 h-5 text-emerald-600 mt-0.5 shrink-0" />
                    )}

                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className="font-semibold text-sm">{n.title}</h4>
                        {!n.isRead && <Badge className="bg-emerald-500 text-slate-950 text-[10px]">NEW</Badge>}
                      </div>
                      <p className="text-xs mt-1 text-slate-600">{n.message}</p>
                      <span className="text-[10px] text-slate-500 block mt-1">{n.timestamp}</span>
                    </div>
                  </div>

                  {!n.isRead && (
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => handleMarkRead(n.id)}
                      className="text-xs text-emerald-600 hover:text-emerald-700"
                    >
                      Dismiss
                    </Button>
                  )}
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default NotificationCenter;
